Feat: Input switch
MYM-Tech/cornellius-ui pull request #17
Opened 2022-06-24 17:07 UTC by josermarinr

# Description

Feat:  Introducing Input switch
this component can render a basic switch input

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refacto 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentantion 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-06-28 15:07 UTC, Kaoff requested changes

2022-06-28 15:07 UTC, Kaoff commented on src/components/HelloWorld.tsx
> +);
Why are we keeping this anyway ?

2022-06-28 15:07 UTC, Kaoff commented on src/components/Inputs/CorInputSwitch/CorInpurSwitch.module.scss
> +.CorInpurSwitch {
```suggestion
.cor_input_switch {
```

2022-06-28 15:07 UTC, Kaoff commented on src/components/Inputs/CorInputSwitch/CorInpurSwitch.module.scss
> +        @extend .CorInpurSwitch;
```suggestion
        @extend .cor_input_switch;
```

2022-06-28 15:07 UTC, Kaoff commented on src/components/Inputs/CorInputSwitch/CorInpurSwitch.module.scss
> +            @extend .CorInpurSwitch__inline;
```suggestion
            @extend .cor_input_switch__inline;
```

2022-06-28 15:07 UTC, Kaoff commented on src/components/Inputs/CorInputSwitch/CorInputSwitch.stories.mdx
> +| labelPosition | set label position | 'left' | 'right' | | 'left' |
⚠️ This line will break the table. Use commas instead of pipes for the type.

2022-06-28 15:07 UTC, Kaoff commented on src/components/Inputs/CorInputSwitch/CorInputSwitch.stories.tsx
> +const Template: StoryFn = (args) => <CorInputSwitch {...args} />;
We have to be coherent here. Either we do `{...args}` or we keep props the way you did with InputTime.

2022-06-28 15:07 UTC, Kaoff commented on src/components/Inputs/CorInputSwitch/CorInputSwitch.tsx
> +                defaultClass = CSS['CorInpurSwitch__inline--right'];
```suggestion
                defaultClass = CSS['cor_input_switch__inline--right'];
```

2022-06-28 15:07 UTC, Kaoff commented on src/components/Inputs/CorInputSwitch/CorInputSwitch.tsx
> +            defaultClass = CSS.CorInpurSwitch;
```suggestion
            defaultClass = CSS.cor_input_switch;
```

2022-06-28 15:07 UTC, Kaoff commented on src/components/Inputs/CorInputSwitch/CorInputSwitch.tsx
> +            CSS.CorInpurSwitch__switchElement__circle,
```suggestion
            CSS.cor_input_switch__switchElement__circle,
```

2022-08-01 08:10 UTC, josermarinr commented
CSS I préfère camelCase, it's more easy to call from a ts file

2022-08-25 15:22 UTC, Kaoff submitted a review, later dismissed

2022-08-25 16:00 UTC, merged